// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx92xBwx8f6uXgtm-i8yEZbGnLlWXG3zU',
    appId: '1:1035613079878:android:f22bebba2bc8dcd5c97d47',
    messagingSenderId: '1035613079878',
    projectId: 'campus-bus-7ba4e',
    databaseURL: 'https://campus-bus-7ba4e-default-rtdb.firebaseio.com',
    storageBucket: 'campus-bus-7ba4e.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnKj08_HZRaAtULyzP7hPoaV05C_qA5Is',
    appId: '1:1035613079878:web:d9233b76ada9efb7c97d47',
    messagingSenderId: '1035613079878',
    projectId: 'campus-bus-7ba4e',
    authDomain: 'campus-bus-7ba4e.firebaseapp.com',
    databaseURL: 'https://campus-bus-7ba4e-default-rtdb.firebaseio.com',
    storageBucket: 'campus-bus-7ba4e.firebasestorage.app',
    measurementId: 'G-MHHQ1XV6K6',
  );
}
